projektZaliczeniowy/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.contrib.auth.models import User
from django.conf.urls.static import static
from sklint.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutUsView.as_view(), name="about"),
    path("contact-us/", ContactUsView.as_view(), name="contact"),
    path("all-categories/", AllCategoriesView.as_view(), name="allcategories"),
    path("product/<int:id>/", ProductDetailView.as_view(), name="productdetail"),
    path("add-to-cart-<int:id>", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("register/", ClientRegisterView.as_view(), name="clientregistration"),
    path("logout/", ClientLogoutView.as_view(), name="clientlogout"),
    path("login/", ClientLoginView.as_view(), name="clientlogin"),
    path("orderhistory/", OrderHistoryView.as_view(), name="orderhistory"),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sklint/models.py
from django.db import models

from django.contrib.auth.models import User


# Create your models here.


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)


class Category(models.Model):
    title = models.CharField(max_length=150)

    def __str__(self):
        return self.title


class Product(models.Model):
    image = models.ImageField(upload_to="Zdjęcia")
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Cart(models.Model):
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    quantity = models.PositiveIntegerField()
    subtotal = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct: " + str(self.id)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=12)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/about.html
{% extends 'base.html' %}
{% block title %}O nas{% endblock %}

{% block content %}
    <h1>Zajmujemy się sprzedażą części komputerowych</h1>
{% endblock %}

templates/addtocart.html
{% extends 'base.html' %}

{% block title %}Dodaj do koszyka{% endblock %}

{% block content %}
<div class="container">
    <h3>Produkt został dodany do koszyka.</h3>
</div>
{% endblock %}

templates/allcategories.html
{% extends 'base.html' %}

{% block title %}Kategorie{% endblock %}

{% block content %}
<div class="container">
    {% for cat in allcategories %}
    <h4>{{ cat.title }}</h4><hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class='col-md-3'>
            <div class="m-4">
                <h4><a href="{% url 'productdetail' p.id %}">{{ p.title }}</a></h4>
                <img src="{{ p.image.url }}" alt="" class="img-fluid" style="height: 200px; object-fit: cover;">
                <p class="mt=3">Cena: {{ p.price }} PLN</p>
                <a href="{% url 'addtocart' p.id %}" class="btn btn-primary">Dodaj do koszyka</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
</head>

<body>
    <a href="/">Strona główna</a> |
    <a href="/all-categories/">Kategorie</a> |
    <a href="/about/">O nas</a> |
    <a href="/contact-us/">Kontakt</a> |
    <a href="/my-cart/">Mój koszyk</a> |

    {% if request.user.client %}
    <a href="/orderhistory/">Moje zamówienie</a> |
    <a href="/logout/">Wyloguj</a> |
    Witaj {{ request.user.username }}!
    {% else %}
    <a href="/register/">Rejestracja</a> |
    <a href="/login/">Logowanie</a>
    {% endif %}
    <hr>

    {% block content %}
    {% endblock %}
</body>
</html>

templates/checkout.html
{% extends 'base.html' %}

{% block title %}Sprawdź zamówienie{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Zawartość Twojego koszyka:</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Numer w koszyku</th>
                        <th>Nazwa produktu</th>
                        <th>Cena</th>
                        <th>Ilość</th>
                        <th>Suma</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cp.product.title }}</td>
                        <td>{{ cp.price }} PLN</td>
                        <td>{{ cp.quantity }}</td>
                        <td>{{ cp.subtotal }} PLN</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan = "4" class="text">Do zapłaty:</th>
                        <th>{{ cart.total }} PLN</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Złóż zamówienie:</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Złóż zamówienie</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/clientlogin.html
{% extends 'base.html' %}

{% block title %}Logowanie{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Logowanie</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Zaloguj</button>
                {% if error %}
                <li>{{ error }}</li>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/clientregister.html
{% extends 'base.html' %}

{% block title %}Rejestracja{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Rejestracja</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Zarejestruj</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/contactus.html
{% extends 'base.html' %}
{% block title %}Kontakt{% endblock %}

{% block content %}
    <h1>W razie jakichkolwiek pytań, jesteśmy dostępni:</h1>

        <ul>
            <li><p>Poniedziałek: 10:00-18:00</p></li>
            <li><p>Wtorek: 8:00-16:00</p></li>
            <li><p>Środa: 8:00-16:00</p></li>
            <li><p>Czwartek: 8:00-16:00</p></li>
            <li><p>Piątek: 8:00-16:00</p></li>
            <li><p>Sobota: nieczynne</p></li>
            <li><p>Niedziela: nieczynne</p></li>
        </ul>

    <h2>Pod numerami telefonu:</h2>

        <ul>
            <li><p>+48 123456789</p></li>
            <li><p>+48 987654321</p></li>
        </ul>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}Strona główna{% endblock %}

{% block content %}

<div class="container">
    <h1 class="text-center">Witamy na naszej stronie!</h1>
    <hr>
    <div class="row mt-3">
        {% for p in product_list %}
        <div class='col-md-3'>
            <div class="m-4">
                <h3><a href="{% url 'productdetail' p.id %}">{{ p.title }}</a></h3>
                <img src="{{ p.image.url }}" alt="" class="img-fluid" style="height: 200px; object-fit: cover;">
                <p class="mt=3">Cena: {{ p.price }} PLN</p>
                <a href="{% url 'addtocart' p.id %}" class="btn btn-primary">Dodaj do koszyka</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %}Mój koszyk{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Przedmioty w Twoim koszyku:</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>Numer w koszyku</th>
                        <th>Nazwa produktu</th>
                        <th>Cena</th>
                        <th>Ilość</th>
                        <th>Suma</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cp.product.title }}</td>
                        <td>{{ cp.price }} PLN</td>
                        <td>{{ cp.quantity }}</td>
                        <td>{{ cp.subtotal }} PLN</td>
                        <td>
                            <a href="{% url 'managecart' cp.id %}?action=inc"> Dodaj </a>
                            <a href="{% url 'managecart' cp.id %}?action=dcr"> Usuń </a>
                            <a href="{% url 'managecart' cp.id %}?action=rmv"> Usuń wszystkie </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text">Do zapłaty:</th>
                        <th>{{ cart.total }} PLN</th>
                    </tr>
                    <tr>
                        <th><a href="{% url 'checkout' %}">Złóż zamówienie</a></th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/orderhistory.html
{% extends 'base.html' %}
{% block title %}Historia zamówień{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Twoje zamówienia</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>Numer w koszyku</th>
                        <th>ID zamówienia</th>
                        <th>Nazwa produktu</th>
                        <th>Cena</th>
                        <th>Ilość</th>
                        <th>Suma</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cartproduct %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cp.product.title }}</td>
                        <td>{{ cp.price }} PLN</td>
                        <td>{{ cp.quantity }}</td>
                        <td>{{ cp.subtotal }} PLN</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/productdetail.html
{% extends 'base.html' %}
{% block title %}{{ product.title }}{% endblock %}

{% block content %}
<div class="container">
    <h3>{{ product.title }}</h3><hr>
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image.url }}" alt="" class=img-fluid">
        </div>
    </div>
    <div class="col-md-6">
        <h4>Nazwa: {{ product.title }}</h4>
        <h5>Kategoria: {{ product.category }}</h5>
        <h5>Cena: {{ product.price }} PLN</h5>
        <hr>
        <a href="{% url 'addtocart' product.id %}" class="btn btn-info">Dodaj do koszyka</a>
        <hr>
        <p>{{ product.description }}</p>
    </div>

</div>
{% endblock %}